version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/var/www
  frontend:
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm run dev"
    ports:
      - 3000:3000
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: rootpass
      MYSQL_DATABASE: bulletin-board
      MYSQL_ROOT_PASSWORD: rootpass
volumes:
  mysql-volume:
